### ISSUE TITLE
Add support for python3

### ISSUE THREAD

**Issue by sebma** [mrts/ubuntu-old-kernel-cleanup#3]
Hi,
[Python2 is not supported anymore.](https://pythonclock.org/)
And your script does not seem to support python3 yet : 
```bash
$ sudo -H $(which pip3.6) install git+http://github.com/mrts/ubuntu-old-kernel-cleanup.git
Collecting git+http://github.com/mrts/ubuntu-old-kernel-cleanup.git
  Cloning http://github.com/mrts/ubuntu-old-kernel-cleanup.git to /tmp/pip-req-build-ydj2at4f
  Running command git clone -q http://github.com/mrts/ubuntu-old-kernel-cleanup.git /tmp/pip-req-build-ydj2at4f
Building wheels for collected packages: ubuntu-old-kernel-cleanup
  Building wheel for ubuntu-old-kernel-cleanup (setup.py) ... done
  Created wheel for ubuntu-old-kernel-cleanup: filename=ubuntu_old_kernel_cleanup-1.0.0-py3-none-any.whl size=3007 sha256=0af3bb10e6249a0649d66c17cb3f28db11b9e2ca1ade55b9ff81043efdcef82a
  Stored in directory: /tmp/pip-ephem-wheel-cache-sg9gxmun/wheels/97/51/c2/6b902aad2dbf5dec1b98c363386bc3a16cde41f906d2153df0
Successfully built ubuntu-old-kernel-cleanup
Installing collected packages: ubuntu-old-kernel-cleanup
Successfully installed ubuntu-old-kernel-cleanup-1.0.0
```
```python
$ ubuntu-old-kernel-cleanup
Traceback (most recent call last):
  File "/usr/local/bin/ubuntu-old-kernel-cleanup", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ubuntu_old_kernel_cleanup/cleanup.py", line 11, in main
    kernel_packages = list_all_installed_kernel_packages()
  File "/usr/local/lib/python3.6/dist-packages/ubuntu_old_kernel_cleanup/cleanup.py", line 23, in list_all_installed_kernel_packages
    'linux-*').split('\n')
TypeError: a bytes-like object is required, not 'str'
$ echo $?
1
```

Can you please add support for Python3 ?

**Comment by mrts** [comment]
@sebma, thanks for the heads-up! I just ported it to Python 3, please test and reply if it works for you.

**Comment by sebma** [comment]
@mrts Works fine :+1:

**Comment by mrts** [comment]
Thanks for testing :)!
